Arrow realization
kovalenko-Max/UML-Diagram-drawer pull request #1
Opened 2021-04-05 17:18 UTC by kovalenko-Max

2021-04-05 17:23 UTC, sinerger commented on UML Diagram drawer/Arrows/ArrowRealization.cs
> +            Draw(From, To);
Это очень не явно ,что метод рисования вызывается в конструктора . Предлагаю так не делать .

2021-04-05 17:23 UTC, sinerger commented on UML Diagram drawer/Arrows/ArrowSuccession.cs
> +            Draw(From, To);
Аналогичная ситуация.

2021-04-05 17:23 UTC, sinerger commented on UML Diagram drawer/Arrows/ArrowRealization.cs
> +            }
добавь пустую строку

2021-04-05 21:20 UTC, SemBen commented on UML Diagram drawer/Arrows/ArrowRealization.cs
> +            Draw(From, To);
Согласен с Ростиславом

2021-04-05 21:24 UTC, SemBen commented on UML Diagram drawer/Arrows/ArrowRealization.cs
> +            }
для явного окончания if

2021-04-05 21:27 UTC, SemBen commented on UML Diagram drawer/Arrows/ArrowSuccession.cs
> +            Draw(From, To);
+

2021-04-05 21:30 UTC, SemBen requested changes
Отправь фидбек

2021-04-06 18:12 UTC, kovalenko-Max commented on UML Diagram drawer/Arrows/ArrowRealization.cs
> +            Draw(From, To);
Поправил

2021-04-06 18:16 UTC, sinerger requested changes
Ok

2021-04-06 18:18 UTC, SemBen approved these changes
OK

2021-04-06 18:20 UTC, merged