Add new class ArrowAssociation
kovalenko-Max/UML-Diagram-drawer pull request #2
Opened 2021-04-05 21:16 UTC by SemBen

2021-04-05 21:19 UTC, sinerger requested changes
OK

2021-04-06 18:53 UTC, kovalenko-Max approved these changes

2021-04-06 18:53 UTC, kovalenko-Max commented on UML Diagram drawer/ArrowAssociation.cs
> +            DrawStraightBrokenLine();
Add null checks

2021-04-06 18:53 UTC, kovalenko-Max commented on UML Diagram drawer/ArrowAssociation.cs
> +            if (IsHorizontal)
Add null checks

2021-04-06 18:53 UTC, sinerger approved these changes
Ok

2021-04-06 18:55 UTC, merged