From Base to Dev merge
kovalenko-Max/UML-Diagram-drawer pull request #8
Opened 2021-04-08 21:25 UTC by kovalenko-Max

2021-04-09 08:02 UTC, sinerger commented on UML Diagram drawer/Arrows/AbstactArrow.cs
> +        public abstract void CreateSelectionBorders();
Мотод создает коллайдер вокруг обьекта? в интерфейсе для этого есть метод CreateRectangles. Переименуй или тут или там. Инплементируй его через абстаркцию.

2021-04-09 08:03 UTC, sinerger commented on UML Diagram drawer/Arrows/AbstactArrow.cs
> +        public abstract void CreateSelectionBorders();
*без абстракции

2021-04-10 11:01 UTC, sinerger commented on UML Diagram drawer/Arrows/AbstactArrow.cs
> +        public bool IsSelected { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
Убери `=> throw new NotImplementedException();`

2021-04-10 11:03 UTC, sinerger commented on UML Diagram drawer/Arrows/ArrowAggregation.cs
> +            Point[] points = new Point[]
Используй свойство `Points ` . Оно уже инициализировано

2021-04-10 11:06 UTC, sinerger commented on UML Diagram drawer/Forms/AbstactFormClass.cs
> +        public bool IsSelected { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
Удали `=> throw new NotImplementedException();`

2021-04-10 11:10 UTC, sinerger requested changes
Внеси исправления и можно мержить .

2021-04-12 18:28 UTC, kovalenko-Max commented on UML Diagram drawer/Forms/AbstactFormClass.cs
> +        public bool IsSelected { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
Формы ж еще не реализованы.

2021-04-12 18:30 UTC, kovalenko-Max commented on UML Diagram drawer/Arrows/AbstactArrow.cs
> +        public abstract void CreateSelectionBorders();
Так он в интерфейсе и называется CreateSelectionBorders(); Или я не туда смотрю?

2021-04-19 17:44 UTC, sinerger approved these changes
ok

2021-04-20 07:24 UTC, closed without merging